language: ruby
script: bundle exec rake test
rvm:
 - 1.8.7
 - 1.9.3
# - jruby-18mode # JRuby in 1.8 mode
# - jruby-19mode # JRuby in 1.9 mode
env:
 - ROS_MASTER_URI=http://localhost:11311 ROS_PACKAGE_PATH=$HOME RUBYLIB=$HOME/builds/OTL/rosruby/lib
#matrix:
# allow_failures:
#  - rvm: jruby-19mode
